[package]
name = "curtable"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
description="A table view implementation for cursive."
repository = "https://github.com/BonsaiDen/curtable.git"
readme = "README.md"
keywords = ["cursive", "ncurses", "TUI", "UI"]
categories = ["command-line-interface", "gui"]
license = "MIT/Apache-2.0"

[dependencies]
cursive = "0.5"

[dev-dependencies]
rand = "*"

